defaultProject: conversionista-se
defaultLocation: EU
defaultDataset: c_forecast_dev
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0

vars:
  yearly_holidays: '["01-01","01-06","05-01","06-01","12-24","12-25","12-26","12-31"]'
